title: Matias Dahl
author: Matias Dahl
baseurl: ""

date_format: "%m/%Y"

google_analytics:
disqus_shortname:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'no_intra_emphasis']

permalink:    /blog/:year/:title
