title: Matias Dahl
author: Matias Dahl
baseurl: ""

date_format: "%m/%Y"

google_analytics:
disqus_shortname:

# Build settings
markdown:     kramdown
kramdown:
  input: GFM
  # pretty single and double quotes
  smart_quotes:   lsquo,rsquo,ldquo,rdquo 

permalink:    /:year/:title
